spring:
  application:
    name: finance-api
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 20000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI}
          issuer-uri: ${ISSUER_URI}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
keycloak:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    realm: ${KEYCLOAK_ADMIN_REALM}
    server-url: ${KEYCLOAK_ADMIN_SERVER_URL}